{
 "title": "NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Comportamento GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nodejs_gc_duration_seconds_bucket{le=\"0.01\",kind=\"minor\"}",
     "legendFormat": "Minor <= 10ms"
    },
    {
     "expr": "node_nodejs_gc_duration_seconds_bucket{le=\"0.001\",kind=\"minor\"}",
     "legendFormat": "Minor <= 1ms"
    },
    {
     "expr": "node_nodejs_gc_duration_seconds_bucket{le=\"0.001\",kind=\"major\"}",
     "legendFormat": "Major <= 1ms"
    },
    {
     "expr": "node_nodejs_gc_duration_seconds_bucket{le=\"0.01\",kind=\"major\"}",
     "legendFormat": "Major <= 10ms"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(node_nodejs_version_info) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(node_process_start_time_seconds[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_nodejs_heap_space_size_used_bytes",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Quantidade de GC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node_nodejs_gc_duration_seconds_count{kind=\"major\"}",
     "legendFormat": "Qtd GC Major"
    },
    {
     "expr": "node_nodejs_gc_duration_seconds_count{kind=\"minor\"}  ",
     "legendFormat": "Qtd GC Minor"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_process_resident_memory_bytes",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "node_nodejs_heap_size_total_bytes",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "node_nodejs_heap_size_used_bytes",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "node_nodejs_external_memory_bytes",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_nodejs_eventloop_lag_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_process_cpu_seconds_total[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(node_process_cpu_seconds_total[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  }
 ]
}